# Generated by Django 3.2.20 on 2023-09-16 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0010_auto_20230914_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_made',
            name='gst_number',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
